# Generated by Django 4.2.13 on 2026-05-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='deliveries/proof/%Y/%m/'),
        ),
    ]
