# Generated by Django 6.0.4 on 2026-06-14 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_delivery_proof_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
