# Generated by Django 4.2.13 on 2026-05-03 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('midtrans_order_id', models.CharField(max_length=100, unique=True)),
                ('midtrans_transaction_id', models.CharField(blank=True, max_length=100)),
                ('payment_type', models.CharField(blank=True, max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Pembayaran'), ('PAID', 'Sudah Dibayar'), ('FAILED', 'Gagal'), ('EXPIRED', 'Kedaluwarsa')], default='PENDING', max_length=20)),
                ('snap_token', models.CharField(blank=True, max_length=255)),
                ('snap_redirect_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
        ),
    ]
