# Generated by Django 6.0.4 on 2026-06-07 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payment_term_days', models.PositiveIntegerField(default=30)),
                ('is_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cafe', models.OneToOneField(limit_choices_to={'role': 'cafe'}, on_delete=django.db.models.deletion.CASCADE, related_name='credit_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('UNPAID', 'Belum Dibayar'), ('VERIFYING', 'Menunggu Verifikasi'), ('OVERDUE', 'Jatuh Tempo'), ('PAID', 'Lunas')], default='UNPAID', max_length=10)),
                ('payment_method', models.CharField(blank=True, choices=[('MANUAL', 'Transfer Manual'), ('ONLINE', 'Bayar Online')], max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='invoices/proof/%Y/%m/')),
                ('proof_note', models.CharField(blank=True, max_length=200)),
                ('proof_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('snap_token', models.CharField(blank=True, max_length=255)),
                ('snap_redirect_url', models.CharField(blank=True, max_length=500)),
                ('midtrans_order_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_invoices', to=settings.AUTH_USER_MODEL)),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='payments.cafecredit')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_invoice', to='orders.order')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
